apiVersion: v1
kind: Service
metadata:
  name: cats-dogs-service
  labels:
    app: cats-dogs-app
spec:
  type: LoadBalancer
  selector:
    app: cats-dogs-app
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000